'0': '0'
'1': '1'
'170873462630': '170873462630'
'2': '2'
'3': '3'
'428458408537': '428458408537'
ARB: ARB
AURA: AURA
AVAX: AVAX
BAL: BAL
BNB: BNB
BTC.b: BTC
BUSD: USD
CRV: CRV
CVX: CVX
DAI: USD
DOLA: USD
DUCKIES: DUCKIES
DYDX: DYDX
ETH: ETH
GGP: GGP
HOP: HOP
KNC: KNC
LDO: LDO
LUSD: USD
LYRA: LYRA
MAI: USD
MATIC: MATIC
MIM: USD
MaticX: MATIC
PLS: PLS
PT-GLP-28MAR2024: GLP
PT-aUSDC-27JUN2024: USD
QI: QI
RDNT: RDNT
RDNT-WETH: ETH
SD: SD
SDAO: SDAO
SDT: SDT
SONNE: SONNE
SOPH: SOPH
USDC: USD
USDC.e: USD
USDT: USD
USDT.e: USD
USDt: USD
VELO: VELO
VISR: VISR
WAVAX: AVAX
WBTC: BTC
WBTC.e: BTC
WETH: ETH
WETH.e: ETH
WMATIC: MATIC
aPolWETH: ETH
aPolWMATIC: MATIC
agEUR: EUR
crvUSD: USD
esEXA: esEXA
esGMX: GMX
jEUR: EUR
miMATIC: MATIC
sAVAX: AVAX
sUSD: USD
stETH: ETH
stMATIC: MATIC
swETH: ETH
wstETH: ETH
xDai: USD
