'#0': '#0'
ARB: ARB
AURA: AURA
AVAX: AVAX
BAL: BAL
BNB: BNB
BTC.b: WBTC
BUSD: USDC
Blockchain Bliss Sonnet: Blockchain Bliss Sonnet
CRV: CRV
CVX: CVX
DAI: USDC
DOLA: USDC
DUCKIES: DUCKIES
DYDX: DYDX
ETH: ETH
EURA: EURA
EtherMail.io - Web3 wallet email + ENS / UD token: EtherMail.io - Web3 wallet email
  + ENS / UD token
Exchange Pass: Exchange Pass
GGP: GGP
HOP: HOP
KNC: KNC
LDO: LDO
LUSD: USDC
LYRA: LYRA
Limited edition Pirate Girl NFTs at pirategirls.xyz - mint now: Limited edition Pirate
  Girl NFTs at pirategirls.xyz - mint now
MAI: USDC
MATIC: MATIC
MIM: USDC
MaticX: MATIC
Member Node: Member Node
PENDLE: PENDLE
PLS: PLS
PT-GLP-28MAR2024: PT-GLP-28MAR2024
PT-aUSDC-27JUN2024: USDC
QI: QI
RDNT: RDNT
RDNT-WETH: ETH
SD: SD
SDAO: SDAO
SDT: SDT
SONNE: SONNE
SOPH: SOPH
THC World Pass: THC World Pass
USDC: USDC
USDC.e: USDC
USDT: USDC
USDT.e: USDC
USDt: USDC
VELO: VELO
VISR: VISR
WAVAX: AVAX
WBTC: WBTC
WBTC.e: WBTC
WETH: ETH
WETH.e: ETH
WMATIC: MATIC
aPolWETH: ETH
aPolWMATIC: MATIC
agEUR: EURA
crvUSD: USDC
esEXA: esEXA
esGMX: esGMX
jEUR: EURA
miMATIC: MATIC
sAVAX: AVAX
sUSD: USDC
stETH: ETH
stMATIC: MATIC
swETH: ETH
thehighapesclub.com: thehighapesclub.com
wstETH: ETH
xDai: USDC
