input_data:
  database: aiven
  pool_selector:
    reference_asset: usd
    chains: all
    oracle: coingecko
    use_oracle: false
  async:
    gather_limit: 10
    pool_size: 10
    max_overflow: 20
    pool_recycle: 3600
plex:
  update_frequency: 60 # in minutes
  redundant_protocols:
    - LIDO
    - Swell
    - Maker