profile:
  debank_key: "0b9786c662bff596482c995ef9c654aa3663a120"
  addresses:
    - "0x7f8DA5FBD700a134842109c54ABA576D5c3712b8"
    - "0xFaf2A8b5fa78cA2786cEf5F7e19f6942EC7cB531"
input_data:
  raw_data_db:
    type: S3JsonRawDataDB
    bucket_name: actualyield
    data_dir: raw_data # path from home
  plex_db:
    type: sqlite
    bucket_name: actualyield # if not present, look locally, else S3 bucketname.
    remote_file: plex.db # path from home, ignoring key hash
run_parameters:
  async:
    gather_limit: 10
    pool_size: 10
    max_overflow: 20
    pool_recycle: 3600
plex:
  update_frequency: 1 # in minutes
  redundant_protocols:
    - LIDO
    - Swell
    - Maker